server:
  port: 0

spring:
  application:
    name: feign-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: ${spring.application.name}-${random.int[1000,9999]}
    prefer-ip-address: true

