server:
  port: 0

spring:
  application:
    name: eureka-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
#    告知eureka注册中心在收到实例最后一次心跳后，等待多少时间后才能移除该实例
#    该参数不能小于leaseRenewalIntervalInSeconds的值
      lease-expiration-duration-in-seconds: 10
#    告知eureka注册中心 客户端将已多少秒的间隔开始发送心跳以便保证自己处于活跃状态
      lease-renewal-interval-in-seconds: 5



  instance:
    instance-id: ${spring.application.name}-${random.int[1000,9999]}
    prefer-ip-address: true

