server:
  port: 9002

spring:
  application:
    name: feign-client

eureka:
  client:
    service-url:
      defaultZone: http://acexy-tech.eureka:7000/eureka
  instance:
    instance-id: ${spring.application.name}-${random.int[1000,9999]}
    prefer-ip-address: true

